on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  caching:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
      - run: |
          ls
          touch .m2/data.txt
          ls
      - uses: actions/cache@v3
        with:
          path: .m2
          key: this-key
          
  restoring:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
      - uses: actions/cache@v3
        with:
          enableCrossOsArchive: true
          path: .m2
          key: this-key
      - run: |
          ls
          cd .m2
          ls
